import { GoogleGenAI } from "@google/genai";

// FIX: Per coding guidelines, the API key must be obtained from process.env.API_KEY and should be assumed to be present.
// This change fixes the TypeScript error `Property 'env' does not exist on type 'ImportMeta'`.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateSticker = async (prompt: string): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to communicate with the AI service.");
  }
};
